// <auto-generated />
using Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Db.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230114074056_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Db.Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Armor")
                        .HasColumnType("integer")
                        .HasColumnName("armor");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("integer")
                        .HasColumnName("attack_modifier");

                    b.Property<int>("AttacksPerRound")
                        .HasColumnType("integer")
                        .HasColumnName("attacks_per_round");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("integer")
                        .HasColumnName("damage_modifier");

                    b.Property<int>("DiceSize")
                        .HasColumnType("integer")
                        .HasColumnName("dice_size");

                    b.Property<int>("Health")
                        .HasColumnType("integer")
                        .HasColumnName("health");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("RollsCount")
                        .HasColumnType("integer")
                        .HasColumnName("rolls_count");

                    b.HasKey("Id")
                        .HasName("pk_monsters");

                    b.ToTable("monsters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Armor = 13,
                            AttackModifier = 4,
                            AttacksPerRound = 1,
                            DamageModifier = 2,
                            DiceSize = 8,
                            Health = 50,
                            Name = "Wolf",
                            RollsCount = 2
                        },
                        new
                        {
                            Id = 2,
                            Armor = 11,
                            AttackModifier = 2,
                            AttacksPerRound = 1,
                            DamageModifier = 2,
                            DiceSize = 8,
                            Health = 50,
                            Name = "Sea elf",
                            RollsCount = 2
                        },
                        new
                        {
                            Id = 3,
                            Armor = 11,
                            AttackModifier = 2,
                            AttacksPerRound = 1,
                            DamageModifier = 1,
                            DiceSize = 8,
                            Health = 35,
                            Name = "Hyena",
                            RollsCount = 1
                        },
                        new
                        {
                            Id = 4,
                            Armor = 15,
                            AttackModifier = 4,
                            AttacksPerRound = 1,
                            DamageModifier = 0,
                            DiceSize = 8,
                            Health = 70,
                            Name = "Gnoll",
                            RollsCount = 5
                        },
                        new
                        {
                            Id = 5,
                            Armor = 17,
                            AttackModifier = 3,
                            AttacksPerRound = 1,
                            DamageModifier = 0,
                            DiceSize = 6,
                            Health = 60,
                            Name = "Flying sword",
                            RollsCount = 5
                        },
                        new
                        {
                            Id = 6,
                            Armor = 15,
                            AttackModifier = 3,
                            AttacksPerRound = 1,
                            DamageModifier = 0,
                            DiceSize = 8,
                            Health = 50,
                            Name = "Orond Gralhund",
                            RollsCount = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
